# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andriish/Projects/delphes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andriish/Projects/delphes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andriish/Projects/delphes/CMakeFiles /home/andriish/Projects/delphes//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andriish/Projects/delphes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DelphesDisplay

# Build rule for target.
DelphesDisplay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DelphesDisplay
.PHONY : DelphesDisplay

# fast build rule for target.
DelphesDisplay/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DelphesDisplay.dir/build.make CMakeFiles/DelphesDisplay.dir/build
.PHONY : DelphesDisplay/fast

#=============================================================================
# Target rules for targets named Delphes

# Build rule for target.
Delphes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Delphes
.PHONY : Delphes

# fast build rule for target.
Delphes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Delphes.dir/build.make CMakeFiles/Delphes.dir/build
.PHONY : Delphes/fast

#=============================================================================
# Target rules for targets named classes

# Build rule for target.
classes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 classes
.PHONY : classes

# fast build rule for target.
classes/fast:
	$(MAKE) $(MAKESILENT) -f classes/CMakeFiles/classes.dir/build.make classes/CMakeFiles/classes.dir/build
.PHONY : classes/fast

#=============================================================================
# Target rules for targets named ClassesDict

# Build rule for target.
ClassesDict: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ClassesDict
.PHONY : ClassesDict

# fast build rule for target.
ClassesDict/fast:
	$(MAKE) $(MAKESILENT) -f classes/CMakeFiles/ClassesDict.dir/build.make classes/CMakeFiles/ClassesDict.dir/build
.PHONY : ClassesDict/fast

#=============================================================================
# Target rules for targets named lhco2root

# Build rule for target.
lhco2root: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lhco2root
.PHONY : lhco2root

# fast build rule for target.
lhco2root/fast:
	$(MAKE) $(MAKESILENT) -f converters/CMakeFiles/lhco2root.dir/build.make converters/CMakeFiles/lhco2root.dir/build
.PHONY : lhco2root/fast

#=============================================================================
# Target rules for targets named hepmc2pileup

# Build rule for target.
hepmc2pileup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hepmc2pileup
.PHONY : hepmc2pileup

# fast build rule for target.
hepmc2pileup/fast:
	$(MAKE) $(MAKESILENT) -f converters/CMakeFiles/hepmc2pileup.dir/build.make converters/CMakeFiles/hepmc2pileup.dir/build
.PHONY : hepmc2pileup/fast

#=============================================================================
# Target rules for targets named root2lhco

# Build rule for target.
root2lhco: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 root2lhco
.PHONY : root2lhco

# fast build rule for target.
root2lhco/fast:
	$(MAKE) $(MAKESILENT) -f converters/CMakeFiles/root2lhco.dir/build.make converters/CMakeFiles/root2lhco.dir/build
.PHONY : root2lhco/fast

#=============================================================================
# Target rules for targets named pileup2root

# Build rule for target.
pileup2root: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pileup2root
.PHONY : pileup2root

# fast build rule for target.
pileup2root/fast:
	$(MAKE) $(MAKESILENT) -f converters/CMakeFiles/pileup2root.dir/build.make converters/CMakeFiles/pileup2root.dir/build
.PHONY : pileup2root/fast

#=============================================================================
# Target rules for targets named root2pileup

# Build rule for target.
root2pileup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 root2pileup
.PHONY : root2pileup

# fast build rule for target.
root2pileup/fast:
	$(MAKE) $(MAKESILENT) -f converters/CMakeFiles/root2pileup.dir/build.make converters/CMakeFiles/root2pileup.dir/build
.PHONY : root2pileup/fast

#=============================================================================
# Target rules for targets named stdhep2pileup

# Build rule for target.
stdhep2pileup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stdhep2pileup
.PHONY : stdhep2pileup

# fast build rule for target.
stdhep2pileup/fast:
	$(MAKE) $(MAKESILENT) -f converters/CMakeFiles/stdhep2pileup.dir/build.make converters/CMakeFiles/stdhep2pileup.dir/build
.PHONY : stdhep2pileup/fast

#=============================================================================
# Target rules for targets named display

# Build rule for target.
display: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 display
.PHONY : display

# fast build rule for target.
display/fast:
	$(MAKE) $(MAKESILENT) -f display/CMakeFiles/display.dir/build.make display/CMakeFiles/display.dir/build
.PHONY : display/fast

#=============================================================================
# Target rules for targets named DisplayDict

# Build rule for target.
DisplayDict: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DisplayDict
.PHONY : DisplayDict

# fast build rule for target.
DisplayDict/fast:
	$(MAKE) $(MAKESILENT) -f display/CMakeFiles/DisplayDict.dir/build.make display/CMakeFiles/DisplayDict.dir/build
.PHONY : DisplayDict/fast

#=============================================================================
# Target rules for targets named Example1

# Build rule for target.
Example1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Example1
.PHONY : Example1

# fast build rule for target.
Example1/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/Example1.dir/build.make examples/CMakeFiles/Example1.dir/build
.PHONY : Example1/fast

#=============================================================================
# Target rules for targets named CaloGrid

# Build rule for target.
CaloGrid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CaloGrid
.PHONY : CaloGrid

# fast build rule for target.
CaloGrid/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/CaloGrid.dir/build.make examples/CMakeFiles/CaloGrid.dir/build
.PHONY : CaloGrid/fast

#=============================================================================
# Target rules for targets named fastjet

# Build rule for target.
fastjet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fastjet
.PHONY : fastjet

# fast build rule for target.
fastjet/fast:
	$(MAKE) $(MAKESILENT) -f external/fastjet/CMakeFiles/fastjet.dir/build.make external/fastjet/CMakeFiles/fastjet.dir/build
.PHONY : fastjet/fast

#=============================================================================
# Target rules for targets named ExRootAnalysis

# Build rule for target.
ExRootAnalysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExRootAnalysis
.PHONY : ExRootAnalysis

# fast build rule for target.
ExRootAnalysis/fast:
	$(MAKE) $(MAKESILENT) -f external/ExRootAnalysis/CMakeFiles/ExRootAnalysis.dir/build.make external/ExRootAnalysis/CMakeFiles/ExRootAnalysis.dir/build
.PHONY : ExRootAnalysis/fast

#=============================================================================
# Target rules for targets named ExRootAnalysisDict

# Build rule for target.
ExRootAnalysisDict: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExRootAnalysisDict
.PHONY : ExRootAnalysisDict

# fast build rule for target.
ExRootAnalysisDict/fast:
	$(MAKE) $(MAKESILENT) -f external/ExRootAnalysis/CMakeFiles/ExRootAnalysisDict.dir/build.make external/ExRootAnalysis/CMakeFiles/ExRootAnalysisDict.dir/build
.PHONY : ExRootAnalysisDict/fast

#=============================================================================
# Target rules for targets named Hector

# Build rule for target.
Hector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Hector
.PHONY : Hector

# fast build rule for target.
Hector/fast:
	$(MAKE) $(MAKESILENT) -f external/Hector/CMakeFiles/Hector.dir/build.make external/Hector/CMakeFiles/Hector.dir/build
.PHONY : Hector/fast

#=============================================================================
# Target rules for targets named HepMC3

# Build rule for target.
HepMC3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HepMC3
.PHONY : HepMC3

# fast build rule for target.
HepMC3/fast:
	$(MAKE) $(MAKESILENT) -f external/HepMC3/CMakeFiles/HepMC3.dir/build.make external/HepMC3/CMakeFiles/HepMC3.dir/build
.PHONY : HepMC3/fast

#=============================================================================
# Target rules for targets named G__HepMC3rootIO

# Build rule for target.
G__HepMC3rootIO: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 G__HepMC3rootIO
.PHONY : G__HepMC3rootIO

# fast build rule for target.
G__HepMC3rootIO/fast:
	$(MAKE) $(MAKESILENT) -f external/HepMC3/CMakeFiles/G__HepMC3rootIO.dir/build.make external/HepMC3/CMakeFiles/G__HepMC3rootIO.dir/build
.PHONY : G__HepMC3rootIO/fast

#=============================================================================
# Target rules for targets named tcl

# Build rule for target.
tcl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcl
.PHONY : tcl

# fast build rule for target.
tcl/fast:
	$(MAKE) $(MAKESILENT) -f external/tcl/CMakeFiles/tcl.dir/build.make external/tcl/CMakeFiles/tcl.dir/build
.PHONY : tcl/fast

#=============================================================================
# Target rules for targets named PUPPI

# Build rule for target.
PUPPI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PUPPI
.PHONY : PUPPI

# fast build rule for target.
PUPPI/fast:
	$(MAKE) $(MAKESILENT) -f external/PUPPI/CMakeFiles/PUPPI.dir/build.make external/PUPPI/CMakeFiles/PUPPI.dir/build
.PHONY : PUPPI/fast

#=============================================================================
# Target rules for targets named TrackCovariance

# Build rule for target.
TrackCovariance: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TrackCovariance
.PHONY : TrackCovariance

# fast build rule for target.
TrackCovariance/fast:
	$(MAKE) $(MAKESILENT) -f external/TrackCovariance/CMakeFiles/TrackCovariance.dir/build.make external/TrackCovariance/CMakeFiles/TrackCovariance.dir/build
.PHONY : TrackCovariance/fast

#=============================================================================
# Target rules for targets named FastJetDict

# Build rule for target.
FastJetDict: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FastJetDict
.PHONY : FastJetDict

# fast build rule for target.
FastJetDict/fast:
	$(MAKE) $(MAKESILENT) -f modules/CMakeFiles/FastJetDict.dir/build.make modules/CMakeFiles/FastJetDict.dir/build
.PHONY : FastJetDict/fast

#=============================================================================
# Target rules for targets named modules

# Build rule for target.
modules: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 modules
.PHONY : modules

# fast build rule for target.
modules/fast:
	$(MAKE) $(MAKESILENT) -f modules/CMakeFiles/modules.dir/build.make modules/CMakeFiles/modules.dir/build
.PHONY : modules/fast

#=============================================================================
# Target rules for targets named Pythia8Dict

# Build rule for target.
Pythia8Dict: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pythia8Dict
.PHONY : Pythia8Dict

# fast build rule for target.
Pythia8Dict/fast:
	$(MAKE) $(MAKESILENT) -f modules/CMakeFiles/Pythia8Dict.dir/build.make modules/CMakeFiles/Pythia8Dict.dir/build
.PHONY : Pythia8Dict/fast

#=============================================================================
# Target rules for targets named ModulesDict

# Build rule for target.
ModulesDict: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ModulesDict
.PHONY : ModulesDict

# fast build rule for target.
ModulesDict/fast:
	$(MAKE) $(MAKESILENT) -f modules/CMakeFiles/ModulesDict.dir/build.make modules/CMakeFiles/ModulesDict.dir/build
.PHONY : ModulesDict/fast

#=============================================================================
# Target rules for targets named DelphesHepMC3

# Build rule for target.
DelphesHepMC3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DelphesHepMC3
.PHONY : DelphesHepMC3

# fast build rule for target.
DelphesHepMC3/fast:
	$(MAKE) $(MAKESILENT) -f readers/CMakeFiles/DelphesHepMC3.dir/build.make readers/CMakeFiles/DelphesHepMC3.dir/build
.PHONY : DelphesHepMC3/fast

#=============================================================================
# Target rules for targets named DelphesHepMC2

# Build rule for target.
DelphesHepMC2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DelphesHepMC2
.PHONY : DelphesHepMC2

# fast build rule for target.
DelphesHepMC2/fast:
	$(MAKE) $(MAKESILENT) -f readers/CMakeFiles/DelphesHepMC2.dir/build.make readers/CMakeFiles/DelphesHepMC2.dir/build
.PHONY : DelphesHepMC2/fast

#=============================================================================
# Target rules for targets named DelphesPythia8

# Build rule for target.
DelphesPythia8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DelphesPythia8
.PHONY : DelphesPythia8

# fast build rule for target.
DelphesPythia8/fast:
	$(MAKE) $(MAKESILENT) -f readers/CMakeFiles/DelphesPythia8.dir/build.make readers/CMakeFiles/DelphesPythia8.dir/build
.PHONY : DelphesPythia8/fast

#=============================================================================
# Target rules for targets named DelphesLHEF

# Build rule for target.
DelphesLHEF: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DelphesLHEF
.PHONY : DelphesLHEF

# fast build rule for target.
DelphesLHEF/fast:
	$(MAKE) $(MAKESILENT) -f readers/CMakeFiles/DelphesLHEF.dir/build.make readers/CMakeFiles/DelphesLHEF.dir/build
.PHONY : DelphesLHEF/fast

#=============================================================================
# Target rules for targets named DelphesROOT

# Build rule for target.
DelphesROOT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DelphesROOT
.PHONY : DelphesROOT

# fast build rule for target.
DelphesROOT/fast:
	$(MAKE) $(MAKESILENT) -f readers/CMakeFiles/DelphesROOT.dir/build.make readers/CMakeFiles/DelphesROOT.dir/build
.PHONY : DelphesROOT/fast

#=============================================================================
# Target rules for targets named DelphesSTDHEP

# Build rule for target.
DelphesSTDHEP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DelphesSTDHEP
.PHONY : DelphesSTDHEP

# fast build rule for target.
DelphesSTDHEP/fast:
	$(MAKE) $(MAKESILENT) -f readers/CMakeFiles/DelphesSTDHEP.dir/build.make readers/CMakeFiles/DelphesSTDHEP.dir/build
.PHONY : DelphesSTDHEP/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ClassesDict"
	@echo "... DisplayDict"
	@echo "... ExRootAnalysisDict"
	@echo "... FastJetDict"
	@echo "... G__HepMC3rootIO"
	@echo "... ModulesDict"
	@echo "... Pythia8Dict"
	@echo "... CaloGrid"
	@echo "... Delphes"
	@echo "... DelphesDisplay"
	@echo "... DelphesHepMC2"
	@echo "... DelphesHepMC3"
	@echo "... DelphesLHEF"
	@echo "... DelphesPythia8"
	@echo "... DelphesROOT"
	@echo "... DelphesSTDHEP"
	@echo "... ExRootAnalysis"
	@echo "... Example1"
	@echo "... Hector"
	@echo "... HepMC3"
	@echo "... PUPPI"
	@echo "... TrackCovariance"
	@echo "... classes"
	@echo "... display"
	@echo "... fastjet"
	@echo "... hepmc2pileup"
	@echo "... lhco2root"
	@echo "... modules"
	@echo "... pileup2root"
	@echo "... root2lhco"
	@echo "... root2pileup"
	@echo "... stdhep2pileup"
	@echo "... tcl"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

