name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: ["delphes/alma:8", "delphes/fedora:44"]

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build Delphes using make
        run: |
          make distclean
          make -j 8 HAS_PYTHIA8=true

      - name: Run tests
        run: |
          pytest tests

      - name: Build Delphes using cmake
        run: |
          rm -rf build
          mkdir -p build
          cd build
          cmake ..
          make -j 8
